namespace Specification.API.Contracts.TmsDepContract;

public record TmsDepResponse(
    int Id,
    // bool IsReady,
    string NameBrandForPurchase,
    int Count,
   // DateTime DodContract,
    DateTime DodPlan,
    DateTime DodFact,
    decimal PriceNoTax,
    decimal PriceWithTax,
    decimal Amount,
    string AccountNumber,
    DateTime DateAccount,
    //decimal FirstPay,
    //DateTime DateFirstPay,
    //decimal SecondPay,
    //DateTime DateSecondPay,
    //decimal ThirdPay,
    //DateTime DateThirdPay,
    //decimal PaymentBalance,
    //decimal CostOfRefand,
    string Comment,
    Guid DeviceChapterId,
    int ContId,
    Guid? EmpRespId
);

public record TmsDepResponseDetails(
    int Id,
    string NameBrandForPurchase,
   // int[] DodContract,
    int Count,
    int[] DodPlan,
    int[] DodFact,
    decimal PriceNoTax,
    decimal PriceWithTax,
    decimal Amount,
    string AccountNumber,
    int[] DateAccount,
    //decimal FirstPay,
    //int[] DateFirstPay,
    //decimal SecondPay,
    //int[] DateSecondPay,
    //decimal ThirdPay,
    //int[] DateThirdPay,
    //decimal PaymentBalance,
    //decimal CostOfRefand,
    string Comment,
    Guid DeviceChapterId,
    string ContName,
    string ContInn,
    string EmpShortName,
    int ContId,
    Guid? EmpRespId
);
